package org.ics.test;

import javax.naming.Context;
import javax.naming.InitialContext;

import org.ics.ejb.Building;
import org.ics.ejb.Office;
import org.ics.facade.FacadeLocal;

import junit.framework.TestCase;

public class TestFacadeEJB_JUnitEE_Office extends TestCase {

	public TestFacadeEJB_JUnitEE_Office(String name) {
		super(name);
	}

	FacadeLocal facadeLocal;
	
	//No test for primary key, because it's autogenerated.
	String expectedVentilationSetting;
	int expectedTemperatureSetting;
	String expectedBuildingAddress;

	Office office1;
	Office office2;
	Building building;

	protected void setUp() throws Exception {
		super.setUp();
		
		expectedBuildingAddress = "Haparanda";

		Context context = new InitialContext();
		facadeLocal = (FacadeLocal) context.lookup("java:app/EJBSoftwareArchitectureProject/Facade!org.ics.facade.FacadeLocal");
		
		building = new Building(expectedBuildingAddress);
		office1 = new Office(expectedVentilationSetting, expectedTemperatureSetting, building);

	}

	protected void tearDown() throws Exception {
		super.tearDown();

		facadeLocal.deleteBuilding(expectedBuildingAddress);
		facadeLocal = null;

		office1 = null;
		office2 = null;
	}

	public void testFacadeBuilding() {

		office1 = facadeLocal.createOffice(office1);
		expectedOfficeNumber = office1.getOfficeNumber();
		office2 = facadeLocal.findByAddress(expectedOfficeNumber);
		assertEquals(office1.getAddress(), expectedOfficeNumber);
		assertEquals(office2.getAddress(), expectedOfficeNumber);

	}

}
